apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-gha
  namespace: sandbox
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample-nodejs-gha
  template:
    metadata:
      labels:
        app: sample-nodejs-gha
    spec:
      containers:
        - name: sample-nodejs-gha
          image: seonchg/sample-nodejs-gha:main-33cd3ae02de2728931d593ea16bb45492ce60ae1
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
