apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-nodejs-gha
  namespace: sandbox
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample-nodejs-gha
  template:
    metadata:
      labels:
        app: sample-nodejs-gha
    spec:
      containers:
        - name: sample-nodejs-gha
          image: seonchg/sample-nodejs-gha:main-5fcb9fc830dec544bfa3736404fc3180b2b76d91
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
