# Service YAML
apiVersion: v1 
kind: Service
metadata:
  name: sample-nodejs-gha
  namespace: sandbox
spec:
  selector:
    app: sample-nodejs-gha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
